import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import { Footer } from "@/components/Footer";
import { NextAuthProvider } from "@/provider/next-auth-provider";
import { NextAuthStore } from "@/provider/next-auth-store";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextAuthStore>
          <NextAuthProvider>
            <div>
              <div className="flex flex-col h-auto">
                <div className="fixed w-full z-50 bg-white">
                  <Header />
                </div>
                <div className=" xr:pt-[50px] lg:pt-[90px] resHeader:pt-[150px]">
                  {children}
                </div>
              </div>
              <Footer />
            </div>
          </NextAuthProvider>
        </NextAuthStore>
      </body>
    </html>
  );
}
